const preset = (name) => `src/modules/comfy-pipeline/presets/${name}`;

const CHARACTER_PASS_OPTIONAL_TOKENS = [
  { token: "ACTIVE_CHARACTER_ID", description: "Asset identifier for the character generated by the current sequential pass." },
  { token: "ACTIVE_CHARACTER_NAME", description: "Display name for the character generated by the current sequential pass." },
  { token: "ACTIVE_CHARACTER_TRIGGER", description: "Identity-pack trigger word for the active character." },
  { token: "ACTIVE_FACE_REF_PATH", description: "Staged face or view-angle identity reference path for the active character." },
  { token: "ACTIVE_BODY_REF_PATH", description: "Staged body-view identity reference path for the active character." },
  { token: "ACTIVE_HAIR_REF_PATH", description: "Staged back-hair identity reference path for the active character." },
  { token: "ACTIVE_LORA_NAME", description: "LoRA filename selected for the active character and provider." },
  { token: "ACTIVE_LORA_STRENGTH", description: "Scalar LoRA strength for the active character." },
  { token: "PROTECT_PREVIOUS_CHARACTERS", description: "Scalar flag: 1 keeps all earlier accepted character masks protected; 0 is the first pass." }
];

export const BUILTIN_STORYBOARD_WORKFLOWS = [
  {
    id: "storyboard-qwen-stageB", stage: "stageB", quality: "mature_asset_guided",
    workflowJson: preset("storyboard-image-qwen-stageB-v1.json"),
    requiredTokens: ["PROMPT", "SHOT_TITLE", "SEED"].map((token) => ({ token })),
    optionalTokens: [
      ...["SCENE_REF_PATH", "CHAR1_PRIMARY_PATH", "CHAR2_PRIMARY_PATH", "FRAME_IMAGE_PATH", "PASS_B_CHARACTER_MASK_PATH", "CHAR1_NAME", "CHAR2_NAME"].map((token) => ({ token })),
      ...CHARACTER_PASS_OPTIONAL_TOKENS
    ],
    dependencies: [{ kind: "checkpoint", name: "Qwen" }, { kind: "custom_node", name: "TextEncodeQwenImageEditPlusCustom_lrzjason" }],
    output: { nodeType: "SaveImage", extension: "png", filenamePrefix: "storyboard-stageB" }
  },
  {
    id: "storyboard-qwen-stageA", stage: "stageA", quality: "builtin_qwen",
    workflowJson: preset("storyboard-image-qwen-stageA-v1.json"),
    requiredTokens: ["PROMPT", "SHOT_TITLE", "SEED"].map((token) => ({ token })),
    optionalTokens: [
      ...["SCENE_REF_PATH", "CHAR1_PRIMARY_PATH", "FRAME_IMAGE_PATH", "PASS_A_CHARACTER_MASK_PATH", "CHAR1_NAME"].map((token) => ({ token })),
      ...CHARACTER_PASS_OPTIONAL_TOKENS
    ],
    dependencies: [{ kind: "checkpoint", name: "Qwen" }, { kind: "custom_node", name: "TextEncodeQwenImageEditPlusCustom_lrzjason" }],
    output: { nodeType: "SaveImage", extension: "png", filenamePrefix: "storyboard-stageA" }
  },
  {
    id: "storyboard-zimage-turbo", stage: "fallback", quality: "builtin_zimage",
    workflowJson: preset("storyboard-image-zimage-turbo-v1.json"),
    requiredTokens: ["PROMPT", "SHOT_TITLE", "SEED"].map((token) => ({ token })),
    dependencies: [
      { kind: "diffusion_model", name: "z_image_turbo_bf16.safetensors" },
      { kind: "text_encoder", name: "qwen_3_4b.safetensors" },
      { kind: "vae", name: "ae.safetensors" },
      { kind: "node", name: "UNETLoader" },
      { kind: "node", name: "CLIPLoader" },
      { kind: "node", name: "ModelSamplingAuraFlow" }
    ],
    output: { nodeType: "SaveImage", extension: "png", filenamePrefix: "storyboard-zimage" }
  },
  {
    id: "storyboard-single-pass-fallback", stage: "fallback", quality: "single_pass",
    workflowJson: preset("storyboard-image-storyboard-composer-v1.json"),
    requiredTokens: [{ token: "PROMPT" }, { token: "NEGATIVE_PROMPT" }],
    dependencies: [{ kind: "node", name: "CheckpointLoaderSimple" }, { kind: "node", name: "KSampler" }],
    output: { nodeType: "SaveImage", extension: "png", filenamePrefix: "storyboard-fallback" }
  }
];

function values(source) {
  if (!source) return new Set();
  if (typeof source === "string") return new Set([source]);
  if (typeof source[Symbol.iterator] === "function") return new Set(Array.from(source, String));
  return new Set(Object.keys(source));
}

export function inspectWorkflowDefinition(definition, environment = {}) {
  const errors = [];
  if (!definition || !definition.id || !definition.stage || !definition.workflowJson) errors.push({ code: "invalid_definition", message: "Workflow definition is incomplete" });
  const tokens = values(environment.tokens);
  const missingTokens = (definition?.requiredTokens ?? []).map((spec) => typeof spec === "string" ? spec : spec.token).filter((token) => !tokens.has(token) && !tokens.has(`{{${token}}}`));
  for (const token of missingTokens) errors.push({ code: "missing_token", token, message: `Required token is unavailable: ${token}` });
  const dependencyValues = values(environment.availableDependencies ?? environment.dependencies);
  const nodeValues = values(environment.availableNodes ?? environment.nodes);
  const missingDependencies = (definition?.dependencies ?? []).filter((dependency) => dependency.required !== false && !dependencyValues.has(dependency.name) && !((dependency.kind === "node" || dependency.kind === "custom_node") && nodeValues.has(dependency.name)));
  for (const dependency of missingDependencies) errors.push({ code: dependency.kind === "node" || dependency.kind === "custom_node" ? "unavailable_node" : "missing_dependency", dependency, message: `Required dependency is unavailable: ${dependency.name}` });
  return { definition, available: errors.length === 0, errors, missingTokens, missingDependencies };
}

export function selectBestStoryboardWorkflow(reports) {
  const stageRank = { stageB: 3, stageA: 2, fallback: 1 };
  const qualityRank = { mature_asset_guided: 3, builtin_zimage: 2, builtin_qwen: 1, single_pass: 0 };
  const selected = [...reports].filter((report) => report.available).sort((a, b) => stageRank[b.definition.stage] - stageRank[a.definition.stage] || qualityRank[b.definition.quality] - qualityRank[a.definition.quality] || a.definition.id.localeCompare(b.definition.id))[0] ?? null;
  return { selected, rejected: reports.filter((report) => report !== selected) };
}
