export type StoryboardWorkflowStage = "stageA" | "stageB" | "fallback";
export type StoryboardWorkflowQuality = "mature_asset_guided" | "builtin_zimage" | "builtin_qwen" | "single_pass";
export type WorkflowDependencyKind = "checkpoint" | "vae" | "diffusion_model" | "text_encoder" | "controlnet" | "ipadapter" | "custom_node" | "node";

export interface WorkflowTokenSpec {
  token: string;
  required?: boolean;
  description?: string;
}

export const WORKFLOW_TOKEN_DESCRIPTIONS = {
  ACTIVE_CHARACTER_ID: "Asset identifier for the character generated by the current sequential pass.",
  ACTIVE_CHARACTER_NAME: "Display name for the character generated by the current sequential pass.",
  ACTIVE_CHARACTER_TRIGGER: "Identity-pack trigger word for the active character.",
  ACTIVE_FACE_REF_PATH: "Staged face or view-angle identity reference path for the active character.",
  ACTIVE_BODY_REF_PATH: "Staged body-view identity reference path for the active character.",
  ACTIVE_HAIR_REF_PATH: "Staged back-hair identity reference path for the active character.",
  ACTIVE_LORA_NAME: "LoRA filename selected for the active character and provider.",
  ACTIVE_LORA_STRENGTH: "Scalar LoRA strength for the active character.",
  PROTECT_PREVIOUS_CHARACTERS: "Scalar flag: 1 keeps all earlier accepted character masks protected; 0 is the first pass."
} as const;

export interface WorkflowDependency {
  kind: WorkflowDependencyKind;
  name: string;
  required?: boolean;
}

export interface WorkflowOutputSpec {
  nodeId?: string;
  nodeType?: string;
  filenamePrefix?: string;
  extension?: string;
}

export interface StoryboardWorkflowDefinition {
  id: string;
  stage: StoryboardWorkflowStage;
  quality: StoryboardWorkflowQuality;
  workflowJson: string;
  requiredTokens: WorkflowTokenSpec[];
  optionalTokens?: WorkflowTokenSpec[];
  dependencies: WorkflowDependency[];
  output: WorkflowOutputSpec;
}

export type WorkflowCapabilityErrorCode = "missing_token" | "missing_dependency" | "unavailable_node" | "invalid_definition";

export interface WorkflowCapabilityError {
  code: WorkflowCapabilityErrorCode;
  message: string;
  token?: string;
  dependency?: WorkflowDependency;
}

export interface WorkflowEnvironment {
  tokens?: string | Iterable<string> | Record<string, unknown>;
  dependencies?: string | Iterable<string> | Record<string, unknown>;
  availableDependencies?: string | Iterable<string> | Record<string, unknown>;
  nodes?: string | Iterable<string> | Record<string, unknown>;
  availableNodes?: string | Iterable<string> | Record<string, unknown>;
}

export interface WorkflowCapabilityReport {
  definition: StoryboardWorkflowDefinition;
  available: boolean;
  errors: WorkflowCapabilityError[];
  missingTokens: string[];
  missingDependencies: WorkflowDependency[];
}

export interface StoryboardWorkflowSelection {
  selected: WorkflowCapabilityReport | null;
  rejected: WorkflowCapabilityReport[];
}

// The executable implementation is shared with the stock-Node focused check.
// @ts-expect-error The JavaScript runtime is intentionally dependency-free.
import { BUILTIN_STORYBOARD_WORKFLOWS as runtimeWorkflows, inspectWorkflowDefinition as runtimeInspect, selectBestStoryboardWorkflow as runtimeSelect } from "./workflowRegistryRuntime.mjs";

export const BUILTIN_STORYBOARD_WORKFLOWS = runtimeWorkflows as StoryboardWorkflowDefinition[];
export const inspectWorkflowDefinition = runtimeInspect as (definition: StoryboardWorkflowDefinition, environment?: WorkflowEnvironment) => WorkflowCapabilityReport;
export const selectBestStoryboardWorkflow = runtimeSelect as (reports: WorkflowCapabilityReport[]) => StoryboardWorkflowSelection;
